# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoyaDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    pod 'RealmSwift'
    pod 'Moya', '~> 11.0'
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'AlamofireImage', '~> 3.4'
    pod 'PKHUD', '~> 5.0'
    pod "PromiseKit", "~> 6.0"
    pod 'SwiftyJSON', '~> 4.0'
    pod 'SwiftyBeaver'
    pod 'SideMenuSwift'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'iOSDropDown'
    pod 'PopupDialog', '~> 0.9'
    #pod 'ObjectMapper', '~> 3.4'
    pod 'ObjectMapper'

  # Pods for MoyaDemo

end
